// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omuudzhhqxqvxrcwrjag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tdXVkemhocXhxdnhyY3dyamFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTkzNTgsImV4cCI6MjA2Mjg5NTM1OH0.rs6lymhzLygCri0RsnGo5e_jLlzMn2Q2OYwdfvJfkmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);